---
- name: Standard Centos7 Deployment
  hosts: centos7
  become: yes
  tasks:
    - name: Set /etc/hostname
    - name: Set /etc/hosts
    - name: Set /etc/resolv.conf
    - name: Update packages
    - name: Install epel-release
    - name: Install standard packages
    - name: Set up automatic security updates
    - name: Configure ansible user and password
    - name: Configure sudoers
    - name: Configure authorized_keys
    - name: Configure sshd to disallow root logon (PermitRootLogin no)
    - name: Configure sshd to disallow password logons (PasswordAuthentication no)
    - name: Configure sshd to limit user logons (AllowUsers [username1[@source.fqdn]] [username2...])
    - name: Configure 'll' alias
...

# Examples
- lineinfile:
   path: /etc/sudoers
   state: present
   regexp: '^%wheel\s'
   line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: Allow specified groups to sudo
  template: 
    src: sudoers.j2
    dest: /etc/sudoers.d/sudoers
    validate: 'visudo -cf %s'
    mode: 0440

{% for item in base_svr_groups %}
{% if item.sudo %}
%{{ item.name }} ALL=(ALL:ALL) NOPASSWD:ALL
{% endif %}
{% endfor %}

base_svr_groups:
  - name: developers
    groupid: 30000
    sudo: false
  - name: operations
    groupid: 31000
    sudo: true
  - name: qa
    groupid: 32000
    sudo: false