---
# defaults file for arillso.logrotate

# Path to the imclude files
logrotate_include_dir: /etc/logrotate.d

# package name to install logrotate.
logrotate_package: logrotate

# Enable hourly rotation with cron.
logrotate_use_hourly_rotation: false

# logroate for wtmp
logrotate_wtmp:
  logs:
    - /var/log/wtmp
  options:
    - missingok
    - monthly
    - create 0664 root utmp
    - rotate 1

# logroate for btmp
logrotate_btmp:
  logs:
    - /var/log/btmp
  options:
    - missingok
    - monthly
    - create 0660 root utmp
    - rotate 1

# More log files can be added that will log rotate.
# An example of multiple log rotate applications with available settings:
# logrotate_applications:
#   - name: name-your-log-rotate-application
#     definitions:
#       - logs:
#           - /var/log/apt/term.log
#           - /var/log/apt/history.log
#         options:
#           - rotate 12
#           - monthly
#           - missingok
#           - notifempty
#           - compress
logrotate_applications:
  - name: myapp
    definitions:
      - logs:
          - /var/log/myapp.log
        options:
          - daily
          - rotate 3
          - compress