---
- name: Copy vault-encrypted file to hosts
  hosts: all
  tasks:
    - name: Copy file to hosts
      copy:
        src: secret_file.txt
        dest: /root/.secret_file.txt

# Decrypt secret_file.txt by referencing vault password script in ansible-playbook command:
#ansible-playbook -i inventory --vault-password-file get_vault_pass.py copy_secrets.yml