#nginx.yml
---
- name: Install nginx and configure content on web1
  hosts: web1
  tasks:
  - name: Install nginx
    yum:
      name: nginx
      state: installed
  - name: Start and enable nginx
    service:
      name: nginx
      state: started
      enabled: yes
  - name: Extract web content
    unarchive:
      remote_src: yes
      src: /root/nginx.zip
      dest: /usr/share/nginx/html
  - name: Update content
    replace:
      path: /usr/share/nginx/html/index.html
      regexp: 'This is sample html code'
      replace: 'This is KodeKloud Ansible lab'