---
- name: Attempt to create a secret file
  hosts: localhost
  tasks:
    - name: Secret file block
      block:
        - name: Attempt to create a secret file
          file:
            path: /mnt/secret/test
      rescue:
        - debug:
            msg: Unable to create secret file
