- name: Deploy motd template
  template:
    src: motd.j2
    dest: /etc/motd
- name: Install nagios
  yum: name=nagios state=latest
- name: Add hosts entry for nagios server
  lineinfile:
    path: /etc/hosts
    regexp: ' nagios.example.com$'
    line: '10.0.1.143 nagios.example.com'
- name: Create noc user
  user:
    name: noc
- name: Create .ssh directory
  file:
    path: /home/noc/.ssh
    state: directory
    mode: 0600
    owner: noc
    group: noc
- name: Deploy authorized_keys for noc user
  copy:
    src: authorized_keys
    dest: /home/noc/.ssh/authorized_keys
    owner: noc
    group: noc
    mode: 0600
