---
- name: Copy block of text including relevant Ansible facts to hosts
  hosts: node02
  gather_facts: true
  tasks:
    - name: Copy block of text to host
      blockinfile:
        path: /root/facts.txt
        block: |
          This is Ansible managed node {{ ansible_nodename }}
          IP address of host is {{ ansible_all_ipv4_addresses[0] }}
          Its OS family is {{ ansible_os_family }}
        create: yes

    - name: Copy file to index.html
      copy:
        src: /root/facts.txt
        dest: /usr/share/nginx/html/index.html
        remote_src: yes