---

- name: Deploy lamp stack application
  hosts: all
  become: yes
  roles:
    - role: common

# Install and Configure Database
- name: Deploy lamp stack application
  hosts: lamp-db
  become: yes
  roles:
    - role: mysql

- name: Deploy lamp stack application
  hosts: lamp-web
  become: yes
  roles:
    - role: httpd-php